# print("Start")
# try:
#     y = int(input("Enter a number: "))
#     x = 20
# except NameError:
#     print("x ko difine nahi kiya hay")
# except ZeroDivisionError:
#     print("You can not divide by zero")
# # except Exception as e:
# #     print(f"ERROR : {e}")
# else:
#     print(x/y)
# finally:
#     print("I will print")
# print("End")


# assert condition, message

# age = 12
# assert age >= 18, "You can not donate"

# class CustomError(Exception):
#     pass

# def some_function():
#     # ...
#     if some_condition:
#         raise CustomError("An error occurred in some_function")

# try:
#     some_function()
# except CustomError as e:
#     print("Custom error:", e)


x = []
print(x[4])